/*1) Find maximal departure delay in minutes for each airline. Sort results from smallest to largest maximum
delay. Output airline names and values of the delay.*/

```{sql}
select b.Name, max(a.DepDelayMinutes) as max_dep_delay
from al_perf a 
join L_AIRLINE_ID b 
on a.DOT_ID_Reporting_Airline =b.ID
group by b.Name
order by max_dep_delay;
#17 rows returned
```

/*2) Find maximal early departures in minutes for each airline. Sort results from largest to smallest. Output
airline names.*/

```{sql}
select b.Name, min(a.DepDelay) as max_dep_early
from al_perf a 
join L_AIRLINE_ID b 
on a.DOT_ID_Reporting_Airline =b.ID
where a.DepDelay<0
group by b.Name
order by max_dep_early;
#17 rows returned
```

/*3)Rank days of the week by the number of flights performed by all airlines on that day (1 is the busiest).
Output the day of the week names, number of flights and ranks in the rank increasing order.*/

```{sql}
select w.Day as DayName, sum(a.Flights) as NumFlights, dense_rank() over (order by sum(a.Flights) desc) as rnk
from al_perf a
join L_WEEKDAYS w
    on a.DayOfWeek = w.Code
group by w.Day
order by rnk;
#7 rows returned
```

/*4) Find the airport that has the highest average departure delay among all airports. Consider 0 minutes delay
for flights that departed early. Output one line of results: the airport name, code, and average delay.*/

```{sql}
select a2.Name as AirportName, a1.Code as AirportCode, avg(greatest(p.DepDelay, 0)) as AvgDepartureDelay
from al_perf p
join L_AIRPORT_ID a2 on p.OriginAirportID = a2.ID
join L_AIRPORT a1 on a1.Name = a2.Name       
group by a2.Name, a1.Code
order by AvgDepartureDelay desc
limit 1;
# 1 row returned
```

/*5) For each airline find an airport where it has the highest average departure delay. Output an airline name, a
name of the airport that has the highest average delay, and the value of that average delay.*/

```{sql}
with avg_delay as (
    select c.Name as AirlineName, b.Name as AirportName, avg(greatest(a.DepDelay, 0)) as AvgDelay
    from al_perf a
    join L_AIRPORT_ID b on a.OriginAirportID = b.ID
    join L_AIRLINE_ID c on a.DOT_ID_Reporting_Airline = c.ID
    group by c.Name, b.Name
),
ranked as (
    select AirlineName, AirportName, AvgDelay,row_number() over (partition by AirlineName order by AvgDelay desc) as rn
    from avg_delay
)
select AirlineName, AirportName, AvgDelay
from ranked
where rn = 1
order by AirlineName;
#17 rows returned
```

```{sql}
/*6a) Check if your dataset has any canceled flights.*/
select count(*) as NumCanceledFlights
from al_perf
where Cancelled = 1
#1 row returned

/*6b) If it does, what was the most frequent reason for each departure airport? Output airport name,
the most frequent reason, and the number of cancelations for that reason.*/
with cancel_counts as (
    select ap.Name as AirportName, r.Reason as CancelReason, count(*) as NumCancel
    from al_perf a
    join L_AIRPORT_ID ap on a.OriginAirportID = ap.ID
    join L_CANCELATION r on a.CancellationCode = r.Code
    where a.Cancelled = 1
    group by ap.Name, r.Reason
),
ranked as (
    select AirportName, CancelReason, NumCancel,
        row_number() over (partition by AirportName order by NumCancel desc) as rn
    from cancel_counts
)
select AirportName, CancelReason, NumCancel
from ranked
where rn = 1
order by AirportName;
#265 rows returned
```

/*7) Build a report that for each day output average number of flights over the preceding 3 days.*/

```{sql}
with daily_flights as (
    select cast(FlightDate as date) as FlightDate,sum(Flights) as NumFlights
    from al_perf
    group by cast(FlightDate as date)
)

select FlightDate,NumFlights,avg(NumFlights) over (order by FlightDate rows between 3 preceding and 1 preceding  
    ) as AvgFlightsPrev3Days
from daily_flights
order by FlightDate
#32 rows returned
```


